### PR TITLE
implemented conditional import option

### PR DESCRIPTION
**Pull request by bijoshtj**
eg:

import com.abc.x|com.bcd.x|com.cde.x as x;

The above statement during compile time will be updated to 
 (if com.abc.x present) 
import com.abc.x as x
(else if com.bcd.x as x)
import com.bcd.x as x

etc.

### CODE REVIEW

**Comment by rampr** [comment]
LGTM

**Comment by jishnu7** [comment]
I think we should do this in import processor (packages/preprocessors/import.js), since this is not a compile operation.
All files reaching here are already replaced `import xxx` with `jsio('xxx')`

**Comment by bijoshtj** [comment]
i kept functionality here because of 3 reasons.
1. helper functions already defined here. 
2. dynamic import check is doing here oly.
3. again we need to extract opts params there again which is already doing here and using for dynamic imports as well.

So this looks better place. @jishnu7

**Comment by jishnu7** [comment]
We just need to check whether file exist or not. it can be done with fs module. I don't think we need any other functions of this file.

**Comment by bijoshtj** [comment]
closing since implementation moved to preprocessor module. creating new pr.

**Pull request closed without merging**
