### PR TITLE
implemented conditional import feature

### PR DESCRIPTION
**Pull request by bijoshtj**

### CODE REVIEW

**Comment by rampr** [comment]
how will this be used ?

**Comment by rohanhc** [comment]
Looks good. We use | to separate imports?

**Comment by bijoshtj** [comment]
@rampr  

import com.hashcube.x|com.gc.x as X

it will import com.hashcube.x if present, else it will import com.gc.x

**Comment by bijoshtj** [comment]
@rohanhc  Yes .

**Comment by rampr** [comment]
It won't break existing imports right ?

**Comment by rampr** [comment]
Looks Good To Me

**Pull request merged**
